language: ruby
bundler_args: --without debug osx development
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
  - 1.8.7
  - ree
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.8.7
